### PR TITLE
Wiggly Weasels

### PR DESCRIPTION
**Pull request by JetDeveloping**
Thanks for an awesome code jam. I learned so much, and it was an amazing experience.

### CODE REVIEW

**Comment by SebastiaanZ** [comment]
No merge issues.

Flake8 linting errors:
```
./wiggly-weasels/Backend/flashback/fbbackend/urls.py:13:1: E303 too many blank lines (3)
./wiggly-weasels/Backend/flashback/fbbackend/urls.py:15:2: W292 no newline at end of file
./wiggly-weasels/Backend/flashback/fbbackend/admin.py:14:1: E302 expected 2 blank lines, found 1
./wiggly-weasels/Backend/flashback/fbbackend/admin.py:21:1: E303 too many blank lines (3)
./wiggly-weasels/Backend/flashback/fbbackend/tests.py:1:1: F401 'django.test.TestCase' imported but unused
./wiggly-weasels/Backend/flashback/fbbackend/serializers.py:9:54: W291 trailing whitespace
./wiggly-weasels/Backend/flashback/fbbackend/serializers.py:41:1: W391 blank line at end of file
```

**Review by mbaruh — COMMENTED** [review]
Hello Wiggly Weasels, thank you for participating in the code jam!

You have a pretty solid README, with installation instructions, usage instructions, and screenshots. I would have liked to see a few words about the theme of the jam and how your project relates to it, but it's not a big deal.

In your README, you wrote "I will assume that you have npm and Python already installed!" which might be fine in the context of the code jam, but it would be better to think of it as any other open-source project, and make sure the instructions are complete.
This also raises the question of which versions did you use to develop it? It would be appropriate to specify those versions in case any future update is backwards-incompatible with something you did.
These issues could be resolved more easily by containerizing your application with docker for example, and/or using a packaging tool such as pipenv (which is a more solid tool than just using requirements.txt for a variety of reasons, I suggest having a read about it).

Your project didn't have a whole lot of Python code in it, but it looks fairly solid overall. There are a few style issues which I will detail below.

**Comment by JetDeveloping** [comment]
@mbaruh Hey, Zig! Thanks so much for the review, I learned a lot about Pythonic Naming Conventions that I will remember, for sure. I just have one quick question! When you say that Python names should be in PascalCase, do you mean Camal Case? I'm asking the question, because I thought that Python used snake_case.

Anyways, thank you so much for the review, I will definitely take the contents from this review into future competitions and projects!

Stay safe,

Jet

**Comment by mbaruh** [comment]
> 
> 
> @mbaruh Hey, Zig! Thanks so much for the review, I learned a lot about Pythonic Naming Conventions that I will remember, for sure. I just have one quick question! When you say that Python names should be in PascalCase, do you mean Camal Case? I'm asking the question, because I thought that Python used snake_case.
> 
> Anyways, thank you so much for the review, I will definitely take the contents from this review into future competitions and projects!
> 
> Stay safe,
> 
> Jet

Python uses PascalCase for classes, meaning that each initial is uppercase.
camelCase means that the first letter in the first word is lowercase, and the rest is like PascalCase. An easy way to remember that is thinking about how camels have a hump in the middle.

**Pull request merged**
