### PR TITLE
Maniacal-Moths

### PR DESCRIPTION
**Pull request by hot9cups**
The Final App

### CODE REVIEW

**Comment by SebastiaanZ** [comment]
No merge issues.

No flake8 linting errors.

Note for reviewer: This project was made as a solo effort by The Joker (hot9cups) after the other team members dropped out.

**Review by eivl — COMMENTED** [review]
ok code quality. looks a bit short. did the team fall apart during the jam?

**Comment by hot9cups** [comment]
> ok code quality. looks a bit short. did the team fall apart during the jam?

I made the project alone.

**Comment by eivl** [comment]
> > ok code quality. looks a bit short. did the team fall apart during the jam?
> 
> @eivl 
> I made the project alone.

No way. That is impressive.

**Comment by hot9cups** [comment]
> > > ok code quality. looks a bit short. did the team fall apart during the jam?
> > 
> > 
> > @eivl
> > I made the project alone.
> 
> No way. That is impressive.

Hehe, thank you. That was indeed a very testing and challenging period of 10 days.

**Pull request merged**
